.gitignore

chore: Ignore .idea

---

crates/iceberg/src/spec/transform.rs

The main branch failed because of a conflict merge. Fix it.

fix: Fix build break in main branch

---

crates/iceberg/src/spec/datatypes.rs

[comment] should be IEEE 754 rather than 753

---

.github/workflows/ci.yml
crates/iceberg/src/spec/values.rs

fix: Add doc test action

---

rust-toolchain.toml

minor: Upgrade to latest toolchain

---

Cargo.toml
crates/catalog/rest/Cargo.toml
crates/iceberg/Cargo.toml

chroes:Manage dependencies using workspace.

---

crates/iceberg/src/spec/manifest.rs

Close #165 
Second part of this bug fix.

fix: Ignore negative statistics value

---

Cargo.toml
crates/examples/Cargo.toml
crates/examples/README.md
crates/examples/src/rest_catalog_namespace.rs
crates/examples/src/rest_catalog_table.rs
website/src/api.md

This pr add user guide for website.

feat: Add user guide for website.

---

Cargo.toml
crates/catalog/hms/Cargo.toml
crates/catalog/rest/Cargo.toml
crates/examples/Cargo.toml
crates/iceberg/Cargo.toml
crates/test_utils/Cargo.toml

Fix: add required rust version in cargo.toml

---

crates/iceberg/src/catalog/mod.rs

fix: https://github.com/apache/iceberg-rust/issues/166

feat: Add Sync + Send to Catalog trait

---

.github/workflows/publish.yml
Cargo.toml

Close https://github.com/apache/iceberg-rust/issues/214

ci: Add workflow for publish

---

.github/workflows/audit.yml

Resolves https://github.com/apache/iceberg-rust/issues/209.
Workflow file copied directly from https://github.com/apache/arrow-datafusion/blob/main/.github/workflows/audit.yml

Add workflow for cargo audit

---

crates/iceberg/src/spec/manifest.rs
crates/iceberg/src/spec/manifest_list.rs

Issues: https://github.com/apache/iceberg-rust/issues/145
Description: Rename ManifestListEntry as ManifestFile to follow Iceberg Spec and naming convention of Iceberg's Java and Python implementations.

Follow naming convention from Iceberg's Java and Python implementations

---

crates/iceberg/Cargo.toml
crates/iceberg/testdata/file_io_s3/docker-compose.yaml
crates/iceberg/tests/file_io_s3_test.rs

Add minio docker-compose file for test.
Add tests using the minio docker.

test: add FileIO s3 test

---

.cargo/audit.toml

Related to https://github.com/apache/iceberg-rust/issues/221

ci: Ignore RUSTSEC-2023-0071 for no actions to take

---

.gitignore
.idea/.gitignore
.idea/vcs.xml

Add IssueNavigationLink for RustRover

chord:  Add IssueNavigationLink for RustRover

---

crates/iceberg/src/expr/predicate.rs

Closes #150
Implement expression rewriter to remove NOT operator, unblocking expression evaluators like #151.
Added `fn rewrite_not` on Predicate.
Yes
No.

add rewrite_not

---

crates/catalog/hms/src/catalog.rs
crates/catalog/rest/src/catalog.rs
crates/iceberg/src/catalog/mod.rs

Fixes https://github.com/apache/iceberg-rust/issues/236.

Rename stat_table to table_exists in Catalog trait

---

crates/iceberg/src/expr/predicate.rs
crates/iceberg/src/expr/term.rs

feat: Complete predicate builders for all operators.

---

crates/catalog/rest/src/catalog.rs

feat: support uri redirect in rest client

---

Cargo.toml
rust-toolchain.toml

chore: upgrade to rust-version 1.77.1

---

crates/iceberg/src/arrow/schema.rs

A reverse version of #258. There exists a similar thing(const, test case) with #258.  So we can merge #258 first and I will rebase this and remove the duplication.

feat: Implement the conversion from Iceberg Schema to Arrow Schema

---

crates/iceberg/src/expr/predicate.rs

This will make sure that we nicely reduce the expression in the inclusive projection visitor: https://github.com/apache/iceberg-rust/blob/de80a2436bb2fbbd5b4ec6bcafd0bd041b263595/crates/iceberg/src/expr/visitors/inclusive_projection.rs#L73
Everyone is invited to comment on my limited 🦀  knowledge

Simplify expression when doing `{and,or}` operations

---

crates/iceberg/src/avro/schema.rs

fix #144
This seems to be changed by mistake in #82. It was correct when initially introduced in #40
Signed-off-by: xxchan <xxchan22f@gmail.com>

fix: use avro fixed to represent decimal

---

crates/catalog/rest/src/catalog.rs

The purpose of this PR is to follow the OAuth property standard as defined in the Java implementation and the REST Catalog specification: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L144-L145.

feat(catalog!): Deprecate rest.authorization-url in favor of oauth2-server-uri

---

crates/iceberg/src/spec/partition.rs
crates/iceberg/src/spec/transform.rs
crates/iceberg/src/transform/temporal.rs

Closes https://github.com/apache/iceberg-rust/issues/478

Alter `Transform::Day` to map partition types to `Date` rather than `Int` for consistency with reference implementation

---

README.md

docs: Add links to dev docs

---

README.md

This PR fix the wrong links in last PR.

chore: Remove typo in README

---

crates/iceberg/src/table.rs

In the Elixir implementation that I'm working on, I need both Table and StaticTable with the Clone trait.

feat(table): Add debug and clone trait to static table struct

---

crates/iceberg/src/arrow/schema.rs

Fix the build break in main branch. We may need merge queue to detect such behavior.

Fix main branch building break

---

crates/iceberg/src/io/storage_s3.rs

io: add support to set assume role session name

---

crates/catalog/sql/Cargo.toml

fix: Update sqlx from 0.8.0 to 0.8.1

---

crates/iceberg/src/spec/schema.rs

fix: Correctly calculate highest_field_id in schema

---

crates/integrations/datafusion/src/table.rs
crates/integrations/datafusion/tests/test_data/TableMetadataV2Valid.json

Adding tests for #650  - to test table provider creation from a static table

test (datafusion): add test for table provider creation

---

README.md

Signed-off-by: xxchan <xxchan22f@gmail.com>

doc: add RisingWave to users

---

crates/iceberg/src/arrow/schema.rs

Also convert the new Utf8View to String type.
Closes #783.

Suport conversion of Arrow Int8 and Int16 to Iceberg Int

---

crates/iceberg/src/arrow/reader.rs
crates/iceberg/src/spec/values.rs
crates/integration_tests/testdata/spark/provision.py
crates/integration_tests/tests/read_evolved_schema.rs

Please don't hold back on my code!

feat: Allow for schema evolution

---

crates/iceberg/src/arrow/reader.rs

Closes #784.
Make use of the projected fields to scope down the arrow schema, and thus potentially avoid some conversions which are not supported yet.

feat: eagerly project the arrow schema to scope out non-selected fields

---

crates/iceberg/src/expr/predicate.rs
crates/iceberg/src/spec/values.rs

And add some nice `.to` conversions. Feel free to roast my Rust code 👍

Chore: Add `AboveMax` and `BelowMin`

---

.cargo/audit.toml
Cargo.lock
crates/integrations/datafusion/Cargo.toml
crates/integrations/datafusion/src/physical_plan/scan.rs

Pick up the latest datafusion version.

chore: datafusion 44 upgrade

---

crates/iceberg/src/spec/manifest.rs

The field is not public, so the change should be safe.

refactor: fix a type in manifest_entries field name

---

crates/catalog/glue/src/catalog.rs

feat(glue): use the same props for creating aws sdk and for FileIO

---

crates/catalog/glue/src/error.rs
crates/catalog/s3tables/src/catalog.rs

Fixes a small spell mistake in error of glue and s3tables catalog

chore(spell): skd -> sdk

---

.github/workflows/audit.yml

https://github.com/apache/iceberg-rust/pull/843#issuecomment-2700081365 @ZENOTME 
Signed-off-by: xxchan <xxchan22f@gmail.com>

fix(ci): fix audit break due to toolchain

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml
.github/ISSUE_TEMPLATE/iceberg_feature.yml

Make willingness in pr template an dropdown rather a checkbox, since it only allows one selection.

Make willingness to contribute in pr template a dropdown

---

bindings/python/Cargo.lock
bindings/python/Cargo.toml
bindings/python/tests/test_transform.py

- Closes #1078.
Enable `chrono-tz` feature in the `arrow` dependency
Thanks to this reference, https://github.com/delta-io/delta-rs/pull/2295
Yes. Unit test coverage using datetime with timezone

Support transforms with datetime timezones

---

CONTRIBUTING.md
Cargo.toml
README.md
rust-toolchain.toml

add info from discussion thread https://lists.apache.org/thread/d10ntkzvkbyvh806063jblhhxgvczoth
- Closes #.

doc: add MSRV and dependency policy doc

---

crates/iceberg/src/spec/values.rs

doc: Clarify use of default map field name

---

Cargo.lock
Cargo.toml
crates/sqllogictest/Cargo.toml
crates/sqllogictest/src/engine/datafusion.rs
crates/sqllogictest/src/engine/mod.rs

- Closes #1212.
Introduces datafusion engine for sqllogictests.
Not yet, will tests later.

Introduce datafusion engine for sqllogictests.

---

crates/iceberg/src/io/file_io.rs
crates/iceberg/src/writer/file_writer/parquet_writer.rs

- Closes #1224.
Skip generating empty parquet files.
UT.

Skip producing empty parquet files

---

Cargo.lock
Cargo.toml

- Closes https://github.com/apache/iceberg-rust/pull/1268

chore: Pin roaring to released version

---

crates/iceberg/src/expr/term.rs

N/A
This PR is to fix typos for 2 functions in the `expr.Reference` doc:
- `is_in()`
- `is_not_in()`
Yes.

docs: fix typo in `expr.Reference` doc

---

scripts/release.sh

- Closes #.
Adds `python3 ./scripts/dependencies.py check` to the release script. This will check dependencies' licenses. Helps prevent issue like #1345 where the `DEPENDENCIES.rust.tsv` files were accidentally removed
Also moved apache license check to the beginning of the release script
Yes, verified by running
```
ICEBERG_VERSION=0.5.0 ICEBERG_VERSION_RC=2 ./scripts/release.sh
```

Run dependency license check in release script

---

crates/catalog/s3tables/DEPENDENCIES.rust.tsv
crates/examples/DEPENDENCIES.rust.tsv
crates/integration_tests/DEPENDENCIES.rust.tsv
crates/integrations/cache-moka/DEPENDENCIES.rust.tsv
crates/integrations/cli/DEPENDENCIES.rust.tsv
crates/sqllogictest/DEPENDENCIES.rust.tsv
crates/test_utils/DEPENDENCIES.rust.tsv
deny.toml
scripts/dependencies.py

- Depends on #1366
Instead of hardcoding a few repos to check in `dependencies.py`, lets walk down all subdirectories and get all with `Cargo.toml` file. This is more future proof in case we add new crates. 
We also need to regenerate license for 0.5.0 
```
python3 ../scripts/dependencies.py check
python3 ../scripts/dependencies.py generate
```
which added 7 new files:
```
crates/catalog/s3tables/DEPENDENCIES.rust.tsv
crates/examples/DEPENDENCIES.rust.tsv
crates/integration_tests/DEPENDENCIES.rust.tsv
crates/integrations/cache-moka/DEPENDENCIES.rust.tsv
crates/integrations/cli/DEPENDENCIES.rust.tsv
crates/sqllogictest/DEPENDENCIES.rust.tsv
crates/test_utils/DEPENDENCIES.rust.tsv
```

Make `dependencies.py` check all subdirectories for cargo toml files

---

CHANGELOG.md

- Related to #1325
Add new PRs since `0.5.0-rc1` to cut the new `0.5.0-rc2`

add new commits to changelog for 0.5.0

---

website/src/release.md

- Closes #.
Minor changes I noticed while verifying 0.6.0-rc1

docs: fix release process docs

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml

Update bug report template with the latest version, 0.6.0
