apache/iceberg-rust

Cargo.toml, src/error.rs, src/lib.rs, src/spec/datatypes.rs, src/spec/mod.rs
This PR adds the support to serialize/deserialize the iceberg datatypes.
=> feat: Implement serialize/deserialize for datatypes

.devcontainer/devcontainer.json, .github/workflows/ci_typos.yml, .licenserc.yaml, CHANGELOG.md, CONTRIBUTING.md, NOTICE, README.md, rustfmt.toml
This PR will add CONTRIBUTING guide for this project and finish the project setup works.
This PR will also close https://github.com/apache/iceberg-rust/issues/10
=> docs: Add CONTRIBUTING and finish project setup

src/spec/datatypes.rs
This PR adds lookup tables for field ids and field names to the StructType. This speeds up the field access for structs with a lot of fields.
=> feat: Add lookup tables to StructType

Cargo.toml, src/error.rs, src/lib.rs, src/spec/mod.rs
This PR introduces error handling for iceberg.
=> feat: Implement error handling

src/spec/datatypes.rs
This change updates the id_lookup table in `StructType` to be a HashMap implementation instead of BTreeMap. Since there won't be a need to do min/max or any kind of ordering, a `BTreeMap` shouldn't be necessary, and lookups for a field based on id can just be done in O(1).
cc: @JanKaul @Xuanwo @Fokko
=> chore: Use HashMap instead of BTreeMap for storing fields by id in StructType

crates/iceberg/src/error.rs
Use macro rules to generate from error code, so that we don't need to repeat for every kind of error.
=> feat: Use macro to define from error.

crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/schema.rs
This refactor introduces two changes:
1. Use `NestedField` in composite types such as struct, map, list to align with java/python implementation.
2. Simplify type ser/de.
=> refactor: Align data type with other implementation.

crates/iceberg/Cargo.toml, crates/iceberg/src/error.rs, crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/schema.rs, crates/iceberg/src/spec/values.rs
=> feat: Define schema post order visitor.

crates/iceberg/src/spec/mod.rs, crates/iceberg/src/spec/transform.rs
This pr doesn't contains actual transform function implementation, since it depends on #20 But it introduces basic transform definition.
=> feat: Add transform

.asf.yaml
Recently we see conflicting merge, and we add this check in github setting to avoid it.
=> fix: Update github configuration to avoid conflicting merge

.gitignore, crates/iceberg/src/spec/values.rs
Close #33 .
Thanks for @Fokko 's suggestion. Add them so that we can make literals more convenient.
=> feat: Add utility methods to help conversion between literals.

crates/iceberg/Cargo.toml, crates/iceberg/src/avro/mod.rs, crates/iceberg/src/avro/schema.rs, crates/iceberg/src/error.rs, crates/iceberg/src/lib.rs, crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/schema.rs, crates/iceberg/testdata/avro_schema_manifest_entry.json, crates/iceberg/testdata/avro_schema_manifest_file_v1.json, crates/iceberg/testdata/avro_schema_manifest_file_v2.json
Introduce conversion between avro schema and iceberg schema.
Currently limitation, due to `apache_avro`'s limit, we can' store attributes in array schema and map schema, this means we will lose `element-id` for list type, and `key-id`, `value-id` for map type. We will fix it later.
Close #37.
=> feat: Introduce conversion between iceberg schema and avro schema

crates/iceberg/src/spec/schema.rs
This change allow Schema Serialzation/Deserialization based on the `into `and `try_from` parameters for serde from a new enum regrouping SchemaV1 and SchemaV2 struct. I added also some helper for conversion between the enum and Schema struct.
The functionality is tested with a new test inside the test section
=> feat: Allow Schema Serialization/deserialization

crates/iceberg/src/spec/snapshot.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/testdata/table_metadata/TableMetadataUnsupportedVersion.json, crates/iceberg/testdata/table_metadata/TableMetadataV1Valid.json, crates/iceberg/testdata/table_metadata/TableMetadataV2CurrentSchemaNotFound.json, crates/iceberg/testdata/table_metadata/TableMetadataV2MissingLastPartitionId.json, crates/iceberg/testdata/table_metadata/TableMetadataV2MissingPartitionSpecs.json, crates/iceberg/testdata/table_metadata/TableMetadataV2MissingSchemas.json, crates/iceberg/testdata/table_metadata/TableMetadataV2MissingSortOrder.json, crates/iceberg/testdata/table_metadata/TableMetadataV2Valid.json, crates/iceberg/testdata/table_metadata/TableMetadataV2ValidMinimal.json
This PR adds integration tests for reading the table metadata from files. Some of the tests are designed to fail. With the current design of the serialization/deserialization the error doesn't specify which field is missing. So I couldn't do a precise check for certain tests.
=> Metadata integration tests

crates/iceberg/Cargo.toml, crates/iceberg/src/error.rs, crates/iceberg/src/io.rs, crates/iceberg/src/lib.rs
Close #49 
In this pr we implement `FileIO` on top of opendal, which provided great abstraction over all kinds of storage. There are still some missing check, but I want to discuss implementation first.
=> feat: Introduce FileIO

crates/iceberg/Cargo.toml, crates/iceberg/src/error.rs, crates/iceberg/src/lib.rs, crates/iceberg/src/transform/bucket.rs, crates/iceberg/src/transform/identity.rs, crates/iceberg/src/transform/mod.rs, crates/iceberg/src/transform/temporal.rs, crates/iceberg/src/transform/truncate.rs, crates/iceberg/src/transform/void.rs
This PR add transform function trait and following implementation:
1. identity
2. void
3. temporal
related issue: #32
=> feat: support transform function

crates/iceberg/src/catalog.rs, crates/iceberg/src/lib.rs
This PR exposes and adds public methods for catalog related structs.
Structs returned by the catalog typically use public methods such as `new()`, `namespace()`, and `name()` to prevent unexpected usage. On the other hand, structs constructed by users often utilize public fields for easier construction, especially when dealing with complex ones.
=> feat: Add public methods for catalog related structs

crates/catalog/rest/Cargo.toml, crates/catalog/rest/src/catalog.rs, crates/catalog/rest/testdata/load_table_response.json, crates/iceberg/Cargo.toml, crates/iceberg/src/catalog/mod.rs, crates/iceberg/src/io.rs, crates/iceberg/src/spec/partition.rs, crates/iceberg/src/spec/schema.rs, crates/iceberg/src/spec/snapshot.rs, crates/iceberg/src/spec/sort.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/table.rs
This pr implements load table in rest catalog, also add accesses to table metadata.
=> feat: Implement load table api.

crates/catalog/rest/src/catalog.rs, crates/iceberg/src/catalog/mod.rs, crates/iceberg/src/io.rs, crates/iceberg/src/rest.rs, crates/iceberg/src/spec/manifest_list.rs, crates/iceberg/src/spec/schema.rs, crates/iceberg/src/table.rs, crates/iceberg/src/transform/bucket.rs, crates/iceberg/src/transform/identity.rs, crates/iceberg/src/transform/temporal.rs, crates/iceberg/src/transform/truncate.rs, crates/iceberg/src/transform/void.rs
Fixes #73 by:
* auto-deriving Debug in cases where all fields are formattable
* providing a manual implementation for cases where fields are not themselves formattable
* Sole case is `ManifestListWriter`'s `avro_writer`, in which case the schema of the writer is the only value printed
=> minor: Provide Debug impl for pub structs #73

crates/iceberg/src/avro/schema.rs, crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/values.rs
This PR:
1. modify to store i128 for Value::Decimal
It make more easy to process Value::Decimal and avoid type consisent problem if we use Decimal.
2. support support ser/deser of value 
3. add related test and fix some wrong in schema
=> feat: support ser/deser of value 

Cargo.toml, crates/iceberg/Cargo.toml, crates/iceberg/src/io.rs, crates/iceberg/src/spec/manifest_list.rs
tempdir is obsolete and relies on remove_dir_all 0.5.3 which has a security vulnerability. Migrate to using tempfile crate instead. References:
- [RUSTSEC-2018-0017](https://rustsec.org/advisories/RUSTSEC-2018-0017)
- [RUSTSEC-2013-0018](https://rustsec.org/advisories/RUSTSEC-2023-0018)
=> fix: Migrate from tempdir to tempfile crate

crates/catalog/rest/src/catalog.rs
Fixes: https://github.com/apache/iceberg-rust/issues/104
I think something was merged in after https://github.com/apache/iceberg-rust/pull/94 without rebasing on top of `main` resulting in some compile failures (type check errors). 
Not a big deal, easily fixed.
=> Fix compile failures

Cargo.toml
`uuid` has fixed recently fixed the bug in `1.6.0`, and dependabot failed to remove the `~` prefix, so I upgrade it by hand.
=> chore: Upgrade uuid manually and remove pinned version

crates/iceberg/src/error.rs, crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/values.rs
Close #117.
We removed type information stored in structs..
=> refactor: Conversion between literal and json should depends on type.

crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/manifest_list.rs
This PR:
1. fix #121 and modify unit test to test this case.
2. fix #119, add init default when reading v1 manifest
3. add test case for writing back v1 manifest/manifest-list as v2 
- for manifest list, we can directly write back a manifest list as v2.
- for manifest, we can call `upgrade_version` and then write it back as v2.
=> fix: fix parse partitions in manifest_list

.asf.yaml
In the ASF yaml. I don't think we should make it a protected branch because I think they overwrite it every time with a force push.
Resolves #137 hopefully!
=> Set `ghp_{pages,path}` properties

crates/iceberg/src/spec/manifest.rs, rust-toolchain.toml
Upgrade to latest stable toolchain.
This will enable nice things such as #139 , hive metastore client.
=> chore: Upgrade toolchain to 1.75.0

README.md
Close #133 .
Adding roadmap and feature status in main page.
This part is heavily inspired by [apache/iceberg-go](https://github.com/apache/iceberg-go).
=> feat: Add roadmap and features status in README.md

.asf.yaml
We don't specify this in `iceberg-python` either.
I got this in my inbox:
The hostname is only used for non-`.apache.org` domains
=> Remove `publish:` section from `.asf.yaml`

CONTRIBUTING.md
=> chore: Update contributing guide.

README.md
File based planning api is done, update the status in README.
=> chore: Update reader api status

Cargo.toml, crates/catalog/hms/Cargo.toml, crates/catalog/rest/Cargo.toml, crates/iceberg/Cargo.toml, crates/test_utils/Cargo.toml
Also includes new changes requested by collaborators ! Let me know if there are changes to be made !
=> #154 : Add homepage to Cargo.toml

crates/iceberg/src/writer/file_writer/mod.rs, crates/iceberg/src/writer/mod.rs
related issue: https://github.com/apache/iceberg-rust/issues/34
It's the part of  #135.
The file writer interface is about the writer for data file format, e.g. parquet, orc.
=> feat: init file writer interface

crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/manifest_list.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/transaction.rs
Resolve #177
Replace `unwrap` with `?` and `expect`.
=> refactor: Replace unwrap

crates/iceberg/src/spec/table_metadata.rs
Add serialize for `TableMetadata` and use `TryFrom` as discussed in #177
=> feat: add handwritten serialize

crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/manifest_list.rs
Closes #179
Once writing works it's probably best to make an integration test that tries to read the manifests.
=> Fix: avro schema names for manifest and manifest_list

Cargo.toml, crates/catalog/hms/Cargo.toml, crates/catalog/hms/src/catalog.rs, crates/catalog/hms/src/utils.rs
Close https://github.com/apache/iceberg-rust/pull/155
=> feat: Bump hive_metastore to use pure rust thrift impl `volo`

Cargo.toml, crates/catalog/hms/DEPENDENCIES.rust.tsv, crates/catalog/rest/DEPENDENCIES.rust.tsv, crates/iceberg/DEPENDENCIES.rust.tsv
We have reached consensus to run the first release: `0.2.0`, see [the discussion](https://lists.apache.org/thread/8sj66kf02qd0qtyyrj4gox3yozjk3vtd) in mail list. 
This is the first step of #180 :
1. Bump version to 0.2.0
2. Update dependencies.
=> feat: Bump version 0.2.0 to prepare for release.

crates/iceberg/src/spec/table_metadata.rs
=> fix: default_partition_spec using the partion_spec_id set

crates/catalog/rest/src/catalog.rs, crates/iceberg/src/catalog/mod.rs, crates/iceberg/src/scan.rs, crates/iceberg/src/spec/snapshot.rs, crates/iceberg/src/spec/table_metadata.rs
This PR aims for issue https://github.com/apache/iceberg-rust/issues/158. Since we don't plan to support the manifest list as manifest list file, we will remove support for it. I remove all `ManifestListLocation::ManifestFiles` and and replace all `ManifestListLocation::ManifestListFile` with `String`.
This PR is linked to https://github.com/apache/iceberg-rust/pull/200 because I accidentally close the previous one :(
=> refactor: remove support of manifest list format as a list of file path

crates/iceberg/src/avro/schema.rs, crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/schema.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/transaction.rs
Remove `unwrap` and `expect`.
It looks like some `expect` are expected.
For example
```rust
pub fn current_snapshot(&self) -> Option<&SnapshotRef> {
self.current_snapshot_id.map(|s| {
self.snapshot_by_id(s)
.expect("Current snapshot id has been set, but doesn't exist in metadata")
})
}
```
Also, it looks like we want this panic to happen.
```rust
pub fn default_sort_order(&self) -> Option<&SortOrderRef> {
if self.default_sort_order_id == DEFAULT_SORT_ORDER_ID {
self.sort_orders.get(&DEFAULT_SORT_ORDER_ID)
} else {
Some(
self.sort_orders
.get(&self.default_sort_order_id)
.expect("Default order id has been set, but not found in table metadata!"),
)
}
}
```
I tried to remove this `expect` in this PR and there will not be an error message.
Do we expect panic here?
=> refactor: remove unwraps

crates/catalog/rest/src/catalog.rs
This number indicates from which release the code was generated. For example, currently new endpoints are added to the spec, but they are not supported by iceberg-rust yet.
=> Fix the REST spec version

crates/catalog/hms/src/catalog.rs
Adds an enum `HmsThriftTransport` to the `HmsCatalogConfig` to allow setting the thrift transport type #188 
Corresponds to the metastore setting `hive.metastore.thrift.framed.transport.enabled` [on the metastore server side](https://issues.apache.org/jira/browse/HIVE-2767).
=> feat: Make thrift transport configurable

crates/catalog/rest/src/catalog.rs, crates/iceberg/src/catalog/mod.rs, crates/iceberg/src/spec/sort.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/transaction.rs
Fixes: https://github.com/apache/iceberg-rust/issues/99
Useful links: 
- [PR to add UnboundSortOrder to Java impl](https://github.com/apache/iceberg/pull/4360)
- [Similar ticket to add UnboundPartitionSpec to Rust impl](https://github.com/apache/iceberg-rust/issues/98)
=> Add UnboundSortOrder

website/src/download.md
Close #213.
Add download page for book.
=> doc: Add download page

crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/values.rs
This minor patch fixes the incorrect `double` API doc and includes a few doc change too.
=> minor: Fix `double` API doc

crates/iceberg/src/expr/mod.rs, crates/iceberg/src/expr/predicate.rs, crates/iceberg/src/expr/term.rs, crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/values.rs
Adds a `negate()` method to `UnboundPredicate`, which will be required as part of #150
=> feat: add `UnboundPredicate::negate()`

crates/iceberg/src/spec/values.rs
Main branch ci failed due to `chrono`  deprecated some methods, fix it by using suggested methods.
=> fix: Remove deprecated methods to pass ci

Cargo.toml, crates/iceberg/Cargo.toml, crates/iceberg/src/arrow.rs, crates/iceberg/src/error.rs, crates/iceberg/src/file_record_batch_reader.rs, crates/iceberg/src/io.rs, crates/iceberg/src/lib.rs, crates/iceberg/src/scan.rs, crates/iceberg/src/spec/manifest.rs
A refactor of @ZENOTME 's PR (https://github.com/apache/iceberg-rust/pull/199) based on some of the comments on that PR. Working and with a test. Completes https://github.com/apache/iceberg-rust/issues/125
EDIT: refactored. inspired by the ArrowReader in the Java implementation. TODO: schema translation
=> Implement basic Parquet data file reading capability

Makefile
Refactor `Makefile` so that it `doc-test` could be included in `unit-test`.
=> chore: doc-test as a target

Cargo.toml, crates/iceberg/Cargo.toml, crates/iceberg/src/io.rs, crates/iceberg/src/scan.rs, crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/writer/file_writer/location_generator.rs, crates/iceberg/src/writer/file_writer/mod.rs, crates/iceberg/src/writer/file_writer/parquet_writer.rs, crates/iceberg/src/writer/file_writer/track_writer.rs
This PR adds a parquet writer under file writer.
=> feat: add parquet writer

.asf.yaml
See discussion in https://github.com/apache/iceberg-rust/issues/113. 
We have more and more contributors, and I want to enable projects so that we can schedule development better.
=> chore: Enable projects.

crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/manifest_list.rs
Rust std doc says ToString shouldn’t be implemented directly. https://doc.rust-lang.org/std/string/trait.ToString.html
=> Implement Display instead of ToString

crates/iceberg/src/catalog/mod.rs, crates/iceberg/src/spec/partition.rs, crates/iceberg/src/spec/table_metadata.rs
This PR init TableMetadataBuilder. Complete #250
=> feat: init TableMetadataBuilder

crates/iceberg/src/table.rs
Implements #246 
The PR adds a `StaticTable` struct that encapsulates `Table` and enables loading a table from meta-data, regardless of a catalog but provides only read-only access to meta-data and scan. 
This aims to provide similar functionality to the StaticTable in pyIceberg and its main value is to make table metadata and scan accessible for various operations using only the metadata.json, in a typesafe way.
Added:
The PR also adds an `into_table()` method that returns the `StaticTable` as a `Table`. In addition, it adds a boolean readonly flag to `Table` which helps to distinguish between a readonly Table built using a StaticTable and a Table loaded from Catalog.
=> feat (static table): implement a read-only table struct loaded from metadata

crates/catalog/rest/src/catalog.rs, crates/catalog/rest/tests/rest_catalog_test.rs
Resolve #238 
The docker image of tabular doesn't support credential settings, so it's impossible to write a test.
I just test it manually using their hosted iceberg service.
=> feat: implement OAuth for catalog rest client

crates/iceberg/src/spec/datatypes.rs
I found these contents are missing while reviewing https://github.com/apache/iceberg-rust/pull/258. Reference from [iceberg spec](https://iceberg.apache.org/spec/#primitive-types)
=> docs: annotate precision and length to primitive types

Cargo.toml, crates/iceberg/src/transform/temporal.rs, crates/iceberg/src/writer/file_writer/parquet_writer.rs
=> build: Restore CI by making parquet and arrow version consistent

crates/iceberg/src/scan.rs, crates/iceberg/src/spec/manifest.rs
resolves #282 
The purpose of the PR is to change the ManifestEntry properties and FileScanTask data_file() method to public in order to enable public access to the file metadata API.
Some consumers are interested in the file paths that are part of the current table and their properties for query and monitoring purposes.
=> fix: enable public access to ManifestEntry properties

crates/iceberg/src/scan.rs, crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/manifest_list.rs
While I'm looking into #286, I found there is one function `add_manifest_entries` which is confusing to me.
In fact, it writes manifest instead of manifest entries. As I think manifest entries (i.e., `ManifestEntry`) should refer to the entries inside manifest (i.e., `Manifest`). I think updating the function names and a few comments make it less confusing.
=> Rename function name to `add_manifests`

crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/schema.rs
Aiming for https://github.com/apache/iceberg-rust/issues/251.
Basically implement `PruneColumn` based on [Java Implementation](https://github.com/apache/iceberg/blob/c07f2aabc0a1d02f068ecf1514d2479c0fbdd3b0/api/src/main/java/org/apache/iceberg/types/PruneColumns.java#L42) and add test cases [PyIceberg](https://github.com/apache/iceberg-python/blob/0ee7f1233e062b17b03fccc1eac6449c72e575f0/tests/test_schema.py#L564-L819)
One question, how to avoid warning like this since it will block `cargo clippy` check? (I did know this warning occurs because I never used `PruneColumn::new()` except test cases).
```bash
warning: associated function `new` is never used
--> crates/iceberg/src/spec/schema.rs:638:8
|
636 | impl PruneColumn {
| ---------------- associated function in this implementation
637 | …
```
=> feat: implement prune column for schema

crates/catalog/hms/src/catalog.rs, crates/catalog/hms/tests/hms_catalog_test.rs
=> fix: HMS Catalog missing properties `fn create_namespace`

crates/iceberg/src/arrow.rs, crates/iceberg/src/scan.rs, crates/iceberg/src/spec/manifest.rs
resolves: #299 
This PR is: 
1. Renames FileScanTask.data_file to data_manifest_entry (it returns `ManifestEntry`)
2. Exposes data_file() on `ManifestEntry`
3. change access to data_file to `FileScanTask.data_manifest_entry().data_file()`
=> fix: renaming FileScanTask.data_file to data_manifest_entry

crates/catalog/rest/src/catalog.rs
resolve https://github.com/apache/iceberg-rust/issues/291
=> feat: Make OAuth token server configurable

crates/catalog/glue/src/catalog.rs, crates/catalog/glue/src/error.rs, crates/catalog/glue/src/utils.rs, crates/catalog/glue/tests/glue_catalog_test.rs
Partly #249 (Task 2/3)
Add support for Glue Catalog, to reach feature parity with other implementations.
- added namespace operations
- also implemented `list_tables` since it's needed for `drop_namespace`
Yes. Unit and integration tests are included.
=> feat: Glue Catalog - namespace operations (2/3)

crates/iceberg/src/spec/values.rs, crates/iceberg/src/transform/bucket.rs, crates/iceberg/src/transform/identity.rs, crates/iceberg/src/transform/mod.rs, crates/iceberg/src/transform/temporal.rs, crates/iceberg/src/transform/truncate.rs, crates/iceberg/src/transform/void.rs
=> feat: add transform_literal

crates/catalog/rest/src/catalog.rs
resolve https://github.com/apache/iceberg-rust/issues/292
=> feat: Support customized header in Rest catalog client

Cargo.toml
#234 used `TimeDelta`
`TimeDelta` was first introduced in [v0.4.34](https://github.com/chronotope/chrono/releases/tag/v0.4.34).
=> fix: chrono dep

crates/iceberg/src/arrow.rs, crates/iceberg/src/scan.rs
We can read Parquet file with `TableScan` as a stream of Arrow `RecordBatches` now. However, it reads all columns without projections of columns. This patch makes `TableScanBuilder.select` work to propagate selected columns to `TableScan` to apply the projection to scan operation.
close #244
=> feat: Read Parquet data file with projection

crates/iceberg/src/transform/temporal.rs
Closes #311
Align timestamp conversion with Java implementation. Unblock #309
- changed `fn day_timestamp_micro`
Yes. Unit tests are included.
=> Fix day timestamp micro

crates/catalog/rest/src/catalog.rs
This is a bit confusing if you come from a Hive background where the warehouse is always a path to hdfs/s3/etc.
With the REST catalog, the warehouse can also be a logical identifier:
https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L72-L78
This means that we have to make sure that we only parse paths that are an actual path, and not an identifier.
I'm open to suggestions. The check is now very simple, but can be extended for example using a regex. But I'm not sure what the implications are of importing additional packages (in Python you want to keep it as lightweight as possible).
=> Support identifier warehouses

crates/iceberg/src/expr/accessor.rs, crates/iceberg/src/expr/mod.rs, crates/iceberg/src/expr/term.rs, crates/iceberg/src/spec/schema.rs, crates/iceberg/src/spec/values.rs, crates/iceberg/src/transform/mod.rs
First PR to come out of breaking up https://github.com/apache/iceberg-rust/pull/241.
Adds `StructAccessor`, which is added to `BoundReference` as a means of retrieving a field's value from a (possibly nested) Struct.
=> Add Struct Accessors to BoundReferences

crates/iceberg/src/expr/mod.rs, crates/iceberg/src/expr/predicate.rs, crates/iceberg/src/expr/visitors/bound_predicate_visitor.rs, crates/iceberg/src/expr/visitors/mod.rs
Alternative implementation for https://github.com/apache/iceberg-rust/pull/320, using per-operator visitor methods
=> Add `BoundPredicateVisitor` (alternate version)

crates/iceberg/src/expr/visitors/bound_predicate_visitor.rs, crates/iceberg/src/expr/visitors/inclusive_projection.rs, crates/iceberg/src/expr/visitors/mod.rs
This PR has been broken out of https://github.com/apache/iceberg-rust/pull/241 as it was getting too large.
The `InclusiveProjection` is used in the process of filtering manifest files in table scans. It projects the `BoundPredicate` that is provided as the filter in a table scan into a Predicate that can be used for filtering the partition specs of manifests.
This also updates `BoundPredicateVisitor` to add a parameter consisting of a reference to the `BoundPredicate` itself to the unary/binary/set operation visitor methods, as a convenience. Without this, the implementation for the `InclusiveProjection` visitor would be much more complex and consist of more boilerplate, as it would need to construct a `BoundPredicate` itself in each method, in order to be able to pass a reference to a …
=> add `InclusiveProjection` Visitor

Cargo.toml, crates/iceberg/Cargo.toml, crates/iceberg/src/writer/base_writer/data_file_writer.rs, crates/iceberg/src/writer/base_writer/mod.rs, crates/iceberg/src/writer/file_writer/mod.rs, crates/iceberg/src/writer/file_writer/parquet_writer.rs, crates/iceberg/src/writer/mod.rs
This PR init the iceberg writer and implement the data file writer. It's the final part of #135.
=> feat: init iceberg writer

crates/iceberg/src/scan.rs
This PR was broken out of https://github.com/apache/iceberg-rust/pull/241 as that PR was getting too large.
It builds on https://github.com/apache/iceberg-rust/pull/322, integrating the `ManifestEvaluator` from that PR into `TableScan` to perform the filtering capability provided by `ManfestEvaluator` on the manifest files in the manifest for the scan's snapshot, rejecting any manifests that don't match the table scan's filter predicate, if present.
=> Implement manifest filtering in `TableScan`

crates/iceberg/src/expr/predicate.rs, crates/iceberg/src/expr/visitors/manifest_evaluator.rs, crates/iceberg/src/scan.rs
Closes #359
The `partition_filter` (inclusive projection) is not only required by the `ManifestEvaluator` but also by the (incoming) `ExpressionEvaluator`. In order to avoid duplicate code as well as unnecessary computation of the partition filters, we should extract the computation of the partition filters and cache the results per partition_spec_id.
With this refactor we (hopefully) should be able to integrate the `ExpressionEvaluator` and the `InclusiveMetricsEvaluator` more easily.
- refactor: Extract and decouple computation of partition filters from construction logic of ManifestEvaluator
- refactor: testsuite ManifestEvaluator
- refactor: add FileScanStreamContext + helper fn to construct partition_spec & schema
- refactor: add thin wrapper for PartitionFileCache & …
=> Refactor: Extract `partition_filters` from `ManifestEvaluator`

crates/iceberg/src/scan.rs
Close #407 
Remove duplicate filter in table scan.
=> fix: Remove duplicate filter

.github/actions/setup-builder/action.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, Makefile, README.md, crates/iceberg/src/avro/schema.rs, crates/iceberg/src/writer/file_writer/parquet_writer.rs, crates/integrations/datafusion/src/schema.rs, rust-toolchain.toml
=> chore: Use nightly toolchain for check

crates/iceberg/src/arrow/reader.rs
For some reason that I don't understand, this change makes the scan work correctly in the scenario described in #495. This change was made to solve the 'Access Denied' problem that was being suppressed, but as a side effect, it solved the problem.
I don't have experience with Rust, so I don't know if this is the correct way to solve this issue, and I don't know enough to write a decent test.
=> fix: Return error on reader task

crates/iceberg/src/io/storage.rs, crates/iceberg/src/io/storage_s3.rs
Currently we are not supporting quite a few attributes in FileIO for S3.
Most important for me is Path-Style-Access. While on it, I added SSE as well.
Java Attributes: https://iceberg.apache.org/javadoc/1.4.1/constant-values.html
Relevant Opendal docs: https://nightlies.apache.org/opendal/opendal-docs-stable/docs/rust/opendal/services/struct.S3.html#server-side-encryption
What I am desperately missing and couldn't implement easily because its missing in Opendal is:
1. Everything around soft-deletes (`s3.delete.*`)
2. Remote signing ("s3.remote-signing-enabled")
@Xuanwo I am not too familiar with Opendal yet. Do you think supporting those would be a large effort?
=> Add additional S3 FileIO Attributes

Cargo.toml, crates/iceberg/src/avro/schema.rs, crates/iceberg/src/spec/datatypes.rs
This PR is preparing for #131. We can merge it when Avro 0.17 released. See  https://issues.apache.org/jira/browse/AVRO-4001
The main fix in avro 0.17 is the missing attribute in the map and list schema. I use the main branch to fix them first:
1. serialize/deserialize the element id in list
2. key-id, value-id in map
3. array map, for now, we can detect using the `LogicalType` attr in avro array schema
=> fix: complete miss attribute for map && list in avro schema

crates/iceberg/src/io/storage_s3.rs
This enables usage of temporary credentials obtained from e.g. aws sts 
closes #528
=> feat(storage): support aws session token

crates/iceberg/src/io/storage_s3.rs
Add support for client.assume-role.arn and
client.assume-role.external-id s3 config properties.
Partial fix for #527
=> io: add support for role arn and external id s3 props

crates/iceberg/tests/file_io_gcs_test.rs, crates/iceberg/tests/file_io_s3_test.rs
Fixes: https://github.com/apache/iceberg-rust/issues/551
=> fix: ensure S3 and GCS integ tests are conditionally compiled only when the storage-s3 and storage-gcs features are enabled

crates/iceberg/README.md
Small typo in the main example for `iceberg`
This would still work, but no doubt `cargo fmt` would alter it everytime for people testing it out :smile:
=> docs: fix main iceberg example

website/src/release.md
This is in line with the paths above, and also with the previous version:
https://dist.apache.org/repos/dist/release/iceberg/
=> Update the paths

.github/workflows/bindings_python_ci.yml, bindings/python/README.md, bindings/python/pyproject.toml
Currently, the dependency management is a bit awkward because we duplicate the list of optional dependencies in `pyproject.toml` under `[project.optional-dependencies]`, and then in `.github/workflows/bindings_python_ci.yml` in order to install the optional dependencies to test the built binary.
Hatch is a lightweight dependency manager that will allow us to manage the dependencies in one place, and reuse the hatch commands in both local development, builds and environment setup in the CI
=> Python: Use hatch for dependency management

crates/iceberg/src/expr/visitors/expression_evaluator.rs, crates/iceberg/src/expr/visitors/inclusive_metrics_evaluator.rs, crates/iceberg/src/expr/visitors/inclusive_projection.rs, crates/iceberg/src/spec/partition.rs, crates/iceberg/src/spec/table_metadata.rs
=> fix: correct partition-id to field-id in UnboundPartitionField

crates/iceberg/src/spec/partition.rs
Adds a few convenience functions for Partitions that are needed for the `TableMetadataBuilder` https://github.com/apache/iceberg-rust/pull/587
=> feat: partition compatibility

crates/catalog/memory/src/catalog.rs, crates/iceberg/src/spec/sort.rs
Reduce clones
I also added two tests that didn't fail but where missing IMO
=> feat: SortOrder methods should take schema ref if possible

crates/iceberg/src/io/storage_s3.rs
Closes https://github.com/apache/iceberg-rust/issues/603
Include the [`client.region`](https://github.com/apache/iceberg/blob/ab2c6f889d07eeee51a1f58605be248e9330d91b/aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java#L67) parameter. This takes precedence over the former `s3.region` configuration, as this does not exist within the Java implemtentation, whereas `client.region` does.
=> feat: add `client.region`

crates/catalog/rest/tests/rest_catalog_test.rs, crates/iceberg/src/io/object_cache.rs, crates/iceberg/src/scan.rs, crates/iceberg/src/spec/sort.rs, crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/transaction.rs
This is a part of the `TableMetadataBuilder` (https://github.com/apache/iceberg-rust/pull/587).
Normalization of TableMetadata does:
* Validate the current schema is set and valid
* Validate that all refs are valid (snapshot exists)
* Validate logs are chronological
* Normalize location (remove trailing slash)
* Validate that for V1 Metadata the `last_sequence_number` is 0
* If the default partition spec is specified but the spec is not present in specs, add it
* If the default sort order is unsorted but the sort order is not present, add it
In Java most of the validations can be found in the constructor:
https://github.com/apache/iceberg/blob/ab2c6f889d07eeee51a1f58605be248e9330d91b/core/src/main/java/org/apache/iceberg/TableMetadata.java#L265
=> Feat: Normalize TableMetadata

crates/iceberg/src/arrow/schema.rs
Previously we only exposed the schema conversion.
=> feat: expose arrow type <-> iceberg type

Cargo.toml, bindings/python/Cargo.toml, crates/iceberg/src/arrow/schema.rs, crates/iceberg/src/expr/visitors/row_group_metrics_evaluator.rs, crates/integrations/datafusion/Cargo.toml
Fixes https://github.com/apache/iceberg-rust/issues/622
~~Needs https://github.com/apache/datafusion/pull/12032 to be released, and then the DataFusion deps to be bumped.~~
Ready to go.
=> Migrate to arrow-* v53

crates/iceberg/src/catalog/mod.rs
Helpful when working with hierarchical namespaces, as `from_vec` is fallible.
=> feat: Add NamespaceIdent.parent()

crates/iceberg/src/arrow/reader.rs, crates/iceberg/src/expr/visitors/page_index_evaluator.rs
=> fix: compile error due to merge stale PR

crates/iceberg/src/scan.rs
Previously TableScan struct was requiring a Snapshot to plan files and for empty tables without a snapshot an error was being returned instead of an empty result.
Following the same approach of Java [0] and Python [1] implementation this commit change the snapshot property to accept None values and the `plan_files` method was also changed to return an empty stream if the snapshot is not present on on PlanContext.
[0] https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/SnapshotScan.java#L119
[1] https://github.com/apache/iceberg-python/blob/main/pyiceberg/table/__init__.py#L1979
Fixes: https://github.com/apache/iceberg-rust/issues/580
=> scan: change ErrorKind when table dont have spanshots

crates/iceberg/src/catalog/mod.rs
The rest-spec specifies sequence-number as optional for TableUpdates:
https://github.com/apache/iceberg/blob/09c737656d316ab6172e0d5ee6920869237e6fd1/open-api/rest-catalog-open-api.yaml#L2319-L2326
In the previous deserialization of updates using `_serde::SnapshotV2` sequence-number is required.
This PR adds a separate deserialization function for catalogs that follows the REST spec.
I got errors from starrocks when writing V1 tables.
=> fix: TableUpdate Snapshot deserialization for v1

crates/iceberg/src/io/storage_gcs.rs
Forwards `gcs.credentials-json` & `gcs.oauth2.token` to opendal.
=> feat: add gcp oauth support

crates/iceberg/src/expr/predicate.rs, crates/integrations/datafusion/src/physical_plan/expr_to_predicate.rs, crates/integrations/datafusion/src/physical_plan/scan.rs, crates/integrations/datafusion/src/table.rs, crates/integrations/datafusion/tests/integration_datafusion_test.rs
fixes: #644 
DataFusion expressions and Iceberg predicates do not have a one-to-one correspondence.
1. Columns and literals are represented as `Expr` in DataFusion, whereas they are merely components of predicates in Iceberg.
2. `And` and `Or` are operators in DataFusion, but they are treated as predicates in Iceberg.
This disparity complicates the transformation process when using `TreeNode`. To address this, I also refactored the code to simplify it.
=> feat(datafusion): Support pushdown more datafusion exprs to Iceberg

crates/iceberg/src/spec/table_metadata_builder.rs
Method TableMetadataBuilder::new_from_metadata was introduced in https://github.com/apache/iceberg-rust/pull/587
This PR aligns a method argument name with the method's documentation comment in L137-140
=> chore: Align argument name with doc comment

crates/iceberg/src/io/storage_s3.rs
Closes #759. 
An example of using this can be found here https://github.com/splitgraph/seafowl/pull/757.
=> feat: expose opendal S3 options for anonymous access

crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/spec/table_metadata_builder.rs
I also noticed that we were handling `properties` and `snapshots` different between V1 and V2 even though they didn't change (have been optional since V1). I also aligned those to treat V1 and V2 equally.
Fixes: https://github.com/apache/iceberg-rust/issues/752
=> fix: current-snapshot-id serialized to -1 in TableMetadata.json

Cargo.toml, crates/puffin/Cargo.toml, crates/puffin/src/compression.rs, crates/puffin/src/lib.rs
Part of https://github.com/apache/iceberg-rust/issues/744
- Add Puffin crate
- Add `CompressionCodec` (see [iceberg/puffin-spec/compression-codecs](https://iceberg.apache.org/puffin-spec/#compression-codecs) for more information)
This is the first of a number of PRs to add support for Iceberg Puffin file format. 
Feel free to ask clarifying questions if anything looks confusing/weird.
Also, it might be helpful to refer to the overarching [PR](https://github.com/apache/iceberg-rust/pull/714) from which these changes were split to understand better how these changes will fit in to the larger picture. 
- Support for LZ4 compression/decompression
- The Java library does not currently support this either. As the Java implementations are the reference implementations in the Iceberg ecosystem, I …
=> feat(puffin): Add Puffin crate and CompressionCodec

crates/integration_tests/testdata/docker-compose.yaml, crates/integration_tests/testdata/spark/Dockerfile, crates/integration_tests/testdata/spark/entrypoint.sh, crates/integration_tests/testdata/spark/provision.py, crates/integration_tests/testdata/spark/spark-defaults.conf, crates/integration_tests/tests/read_positional_deletes.rs
I think it would be good to add Spark to easily generate cases for integration tests. This way we can create tables with positional deletes, branches/tags, deletion vectors, etc.
Maybe we could also avoid adding binary files to the repository, e.g. https://github.com/apache/iceberg-rust/pull/765.
=> Add Spark for integration tests

crates/iceberg/src/spec/mod.rs, crates/iceberg/src/spec/name_mapping.rs
=> name mapping serde

crates/iceberg/src/io/storage_s3.rs
Closes #781.
Parse `S3_DISABLE_CONFIG_LOAD` alongside the other options.
=> feat: Expose disable_config_load opendal S3 option

.asf.yaml
Add a protected branch rule to dismiss stale reviews when new commits are added.
=> infra: Dismiss stale reviews

crates/iceberg/src/spec/transform.rs, crates/iceberg/src/transform/mod.rs, crates/iceberg/src/transform/temporal.rs
Seems to be changed together with `date` transform by mistake in #479
=> fix: return type for year and month transform should be int

crates/iceberg/src/io/storage.rs
I noticed that, when reading many parquet files from S3, one of the reads fails occasionally with a temporary error such as "connection closed before message completed". I think such transient failures are normal for S3, and the client is expected to retry the read in this case. However, opendal was not configured to perform a retry. This commit adds a retry layer to opendal config for S3 and GCS object stores with the default configuration (exponential backoff with up to 3 retries).
This solves the issue for me. It might be useful to make this behavior configurable in the future, but default settings should work most of the time.
=> Retry object store reads on temporary errors.

crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/manifest_list.rs
Our computing way of partitions in the manifest is wrong. It should be a list of field summaries for each partition field in the spec. Each field in the list corresponds to a field in the manifest file’s partition spec. But our implementation is to compute the field summaries of **source column of partition field**. Sorry, this code comes from me originally and this PR fix it.
=> fix: wrong compute of partitions in manifest

crates/iceberg/src/transaction.rs, crates/integration_tests/tests/append_partition_data_file_test.rs
Closes #720 
- Have added test case for base partition data file addition
- Added a test case where different "type" of partition field is set in `DataFileWriterBuilder` when compared to schema
- Added a test case where number of partition fields set in `DataFileWriterBuilder` is different from schema
- Fixed noticed spelling mistakes in `transaction.rs`
=> test: append partition data file

crates/iceberg/src/scan.rs, crates/integration_tests/testdata/spark/entrypoint.sh, crates/integration_tests/testdata/spark/provision.py, crates/integration_tests/tests/read_positional_deletes.rs
Here we fail:
https://github.com/apache/iceberg-rust/blob/74a85e7530e40c56a2a3075be63fd943e632501d/crates/iceberg/src/scan.rs#L449-L454
But then the manifest is already filtered:
https://github.com/apache/iceberg-rust/blob/74a85e7530e40c56a2a3075be63fd943e632501d/crates/iceberg/src/scan.rs#L625
So it is unreachable, and it allows to return invalid data. Instead we should raise an error.
As always, don't hold back on my rust code :)
=> fix: Reading a table with positional deletes should fail

crates/integrations/datafusion/src/physical_plan/scan.rs, crates/integrations/datafusion/tests/integration_datafusion_test.rs
Closes #828.
Return the projected schema instead of the full schema, and thus align with the schema in `ExecutionPlan::schema`.
=> fix(datafusion): Align schemas for DataFusion plan and stream

crates/iceberg/src/io/file_io.rs, crates/iceberg/src/io/storage.rs
~~- This reverts commit cda4a0c595af2606e2f4076e9ef81d79d4428f4b.~~
~~- The scheme of google cloud storage should be `gs` instead of `gcs` and `gs` is not a typo. `gs` is widely used by google and opendal.~~
- support both `gs` and `gcs` schemes for google cloud storage
=> fix: support both gs and gcs schemes for google cloud storage

crates/iceberg/src/io/mod.rs, crates/iceberg/src/io/storage_gcs.rs, crates/iceberg/src/io/storage_s3.rs
- Expose `gcs.disable-config-load`, `gcs.disable-vm-metadata` and `gcs.allow-anonymous` for GCS.
=> feat: Expose disable_config_load opendal GCS option

.github/workflows/audit.yml
1. it installs binary instead of compile
2. add a cron job, and it can automatically create issues like https://github.com/risingwavelabs/risingwave/issues/14002
=> ci: use officail rustsec/audit-check action

crates/catalog/sql/src/catalog.rs
This PR fixes the wrong filter condition in drop table
- Fix sql 
- Add UT to validate the correctness of the drop table
=> fix: fix sql catalog drop table

.github/workflows/ci.yml
alternative to https://github.com/apache/iceberg-rust/pull/824
=> ci: add rust-cache action

crates/iceberg/src/spec/manifest.rs
This PR exposes the _serde::DataFile so that the user can serialize && deserialize the data file. related issue: #774
=> feat: support serialize/deserialize DataFile into avro bytes

crates/iceberg/src/arrow/schema.rs, crates/iceberg/src/writer/file_writer/parquet_writer.rs
I find that the decimal encode for parquet statistic will be byte with var len. Not necessary with 16 len. So we need to extend it when the len smaller than 16.
=> fix: parse var len of decimal for parquet statistic

crates/iceberg/src/inspect/manifests.rs, crates/iceberg/src/inspect/snapshots.rs, crates/iceberg/src/table.rs
Follow-up to https://github.com/apache/iceberg-rust/pull/872#discussion_r1905099231. @Xuanwo suggested we rename `Table::metadata_table` to `Table::inspect`. It agrees with PyIceberg APIs and is more concise.
=> Rename 'metadata_table' to 'inspect'

Cargo.lock, crates/iceberg/Cargo.toml, crates/iceberg/src/inspect/manifests.rs, crates/iceberg/src/inspect/metadata_table.rs, crates/iceberg/src/inspect/snapshots.rs, crates/iceberg/src/table.rs
This changes the metadata table APIs to have `scan()` return streams instead of a single `RecordBatch`.
Context for this is https://github.com/apache/iceberg-rust/pull/863#discussion_r1901545620, where we're adding a metadata table for which we need to read multiple files. @liurenjie1024 suggested we better consume those as stream.
I'm splitting out to discuss the API change separately, even though the existing metadata tables `snapshots` and `manifests` only read a single file we're just returning async streams of a single record batch.
cc @liurenjie1024 @Xuanwo
=> Metadata table scans as streams

crates/iceberg/src/io/object_cache.rs, crates/iceberg/src/scan.rs, crates/iceberg/src/spec/manifest.rs, crates/iceberg/src/spec/snapshot.rs, crates/iceberg/src/transaction.rs
This PR refine the write interface of ManifestWriter according to [ManifestWriter from pyiceberg](https://github.com/apache/iceberg-python/blob/5bef1bfe677df7016dc37b8db87650c34faceb7a/pyiceberg/manifest.py#L829). It add 3 interface `add`, `delete`, `existing` which will rewrite some metadata of manifest entry, e.g. snapshot id, sequence number, file sequence number. 
These refined interfaces are benefit for MergeAppend.( I' m working on it now.
=> refine: refine interface of ManifestWriter

.github/dependabot.yml
I noticed that some groups of dependencies are out of sync: https://github.com/apache/iceberg-rust/pull/915#discussion_r1932478025
Therefore I think it is good to bump the limit a bit (default is 5).
=> Bump number of open Dependabot PRs

crates/iceberg/src/io/storage_s3.rs
Hi, I noticed that this boolean check was inverted, it applied virtual host style access if path style access was true and vice-versa.
=> fix(s3): path-style-access means no virtual-host

crates/iceberg/Cargo.toml, crates/iceberg/src/puffin/blob.rs, crates/iceberg/src/puffin/mod.rs, crates/iceberg/src/puffin/reader.rs, crates/iceberg/src/puffin/test_utils.rs
Part of https://github.com/apache/iceberg-rust/issues/744
- Add PuffinReader
- This is the fourth of a number of PRs to add support for Iceberg Puffin file format. 
- It might be helpful to refer to the overarching [PR](https://github.com/apache/iceberg-rust/pull/714) from which these changes were split to understand better how these changes will fit in to the larger picture. 
- It may also be helpful to refer to the Java reference implementation for PuffinReader [here](https://github.com/apache/iceberg/blob/8cd5b1985d3f9c55ab2ced174559a8416b6ca1b4/core/src/main/java/org/apache/iceberg/puffin/PuffinReader.java#L123).
=> feat(puffin): Add PuffinReader

crates/catalog/s3tables/Cargo.toml, crates/catalog/s3tables/src/catalog.rs, crates/catalog/s3tables/src/lib.rs
Hi!
I was testing s3tables catalog and found that it is not public. I don't know if it was done on purpose, but in order to use it I had to make it public. I also added `TypedBuilder` macro to match the api with other catalogs.
=> fix: Make s3tables catalog public

Cargo.lock
Noticed a small thing when building the project, let me know if that's not right.
=> chore: fix Cargo.lock diff always present after `cargo build`

Cargo.lock, Cargo.toml, crates/iceberg/Cargo.toml, crates/iceberg/src/arrow/record_batch_projector.rs, crates/iceberg/src/writer/base_writer/equality_delete_writer.rs
According to the doc fixed in https://github.com/apache/iceberg/pull/8981, the equality delete writer can have an optional field id. This PR fixes this.
=> fix: allow nullable field of equality delete writer

crates/catalog/rest/src/catalog.rs, crates/catalog/rest/src/client.rs, crates/catalog/rest/src/types.rs
Several of the error messages in `iceberg-catalog-rest` had misleading error messages, so this PR fixes some of those.
Additionally, several of the `Catalog` methods on `RestCatalog` do not accept `StatusCode::OK` as a successful response, so I've added that in as well. This meant that some of the `client.rs` functions had to change, but given that they are only used so many times I thought it was fine to remove the const generics.
There are also a few other things that could be cleaned up but I'll keep this PR short.
=> fix: Misleading error messages in `iceberg-catalog-rest` and allow `StatusCode::OK` in responses

crates/iceberg/src/expr/visitors/page_index_evaluator.rs
Fixes https://github.com/apache/iceberg-rust/issues/605
=> chore: use RowSelection::union from arrow-rs

.github/workflows/release_python.yml
Context: https://github.com/apache/iceberg-rust/pull/948#discussion_r1959179801
Following the changes in https://github.com/apache/opendal/pull/5522 and https://github.com/apache/opendal/issues/5483
Tested github action run on my fork: https://github.com/kevinjqliu/iceberg-rust/actions/runs/13394221916
=> chore(ci): upgrade to manylinux_2_28 for aarch64 Python wheels

.github/actions/overwrite-package-version/action.yml, .github/workflows/release_python.yml, .github/workflows/release_python_nightly.yml
Inspired by [pyiceberg#1601](https://github.com/apache/iceberg-python/pull/1601) & https://github.com/apache/iceberg-python/blob/main/.github/workflows/nightly-pypi-build.yml
This PR adds nightly build of `pyiceberg_core` to testpypi. 
I have successfully tested the github action on my fork by pushing to my own package,
* Action run: https://github.com/kevinjqliu/iceberg-rust/actions/runs/13381378488
* testpypi artifact: https://test.pypi.org/project/pyiceberg-core-kevinliu/
I've also verified library versions locally
```
(3.12.8) ➜  python git:(kevinjqliu/nightly-pyiceberg-core) pip install -i https://test.pypi.org/simple/ pyiceberg-core-kevinliu --prefer-binary --force
Looking in indexes: https://test.pypi.org/simple/
Collecting pyiceberg-core-kevinliu
Using cached …
```
=> [infra] nightly pypi build for `pyiceberg_core`

.github/actions/overwrite-package-version/action.yml, .github/workflows/release_python_nightly.yml
Follow up to #948 
I found a bug in the nightly pypi build where the version timestamp changes within the jobs, causing a single run to push multiple versions. 
This PR fixes the issue by setting the version timestamp once for the entire workflow and then pass it down to individual jobs. This should ensure a consistency version
Workflow run: https://github.com/apache/iceberg-rust/actions/runs/13460497360
Testpypi: https://test.pypi.org/project/pyiceberg-core-kevinliu/#history
Tested on my fork: 
Worfklow run: https://github.com/kevinjqliu/iceberg-rust/actions/runs/13461643730
Testpypi on my fork: https://test.pypi.org/project/pyiceberg-core-kevinliu/0.4.0.dev20250221170617/#files
=> [fix] nightly pypi build for `pyiceberg_core`

crates/iceberg/src/transform/truncate.rs
We found an issue in https://github.com/apache/iceberg-python/pull/1592
=> Check binary array length when applying truncate

.github/workflows/ci.yml
#704 fail in msrv check and I find that's because `cargo update faststr` will update the munge to `0.4.2` instead of `0.4.1`. The simple fix way is to specify the precise version of munge. But I'm not sure whether it's good practice here. Do you have any suggestions for this? cc @Xuanwo @xxchan
=> fix: speficy the version of munge for msrv check

crates/iceberg/src/arrow/reader.rs
Fixes https://github.com/apache/iceberg-rust/issues/1044
=> fix: kleene logic bug

crates/iceberg/src/catalog/mod.rs
=> feat: implement display trait for Ident

crates/iceberg/src/spec/table_metadata.rs, crates/iceberg/src/spec/table_metadata_builder.rs
This PR add a construct_ref to insert the main branch if it's not found in refs. ref from: https://github.com/apache/iceberg-python/blob/f45966208dac7c0a2fbe5b16d643a816db2bacb3/pyiceberg/table/metadata.py#L117
=> feat: add construct_ref for table_metadata

.asf.yaml
Apache infra team has enabled github discussion managed by .asf.yml. Update .asf.yml to enable discussion.
=> Enable discussion.

crates/iceberg/src/spec/view_metadata.rs, crates/iceberg/src/spec/view_metadata_builder.rs
- Closes #1099
- Closes #1100
1. fixes set current view version
2. makes ViewVersionLog::timestamp not consume `self`
1. Added a test which sets current view version to -1
2. doesn't require a test, it's a quality of life improvement
=> fix(views): make timestamp take &self & fix set_current_version_id

crates/catalog/rest/src/catalog.rs, crates/catalog/rest/src/types.rs
- Closes #1096
Implements pagination on the `GET /v1/namespaces` and `GET /v1/namespaces/my_namespace/tables` APIs by looking for a `next-page-token` and adding a `pageToken` query parameter on the next request with that token.
This is allowed on the Iceberg Catalog REST API spec: 
ListTablesResponse: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L3898
ListNamespacesResponse: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L3909
PageToken: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L2009C5-L2029C40
> PageToken:
>       description:
>         An opaque token that allows clients to make use of pagination for list APIs
>         (e.g. ListTables). Clients may initiate the first paginated …
=> Handle pagination via `next-page-token` in REST Catalog

crates/examples/src/rest_catalog_namespace.rs, crates/examples/src/rest_catalog_table.rs
- Closes #1112 .
Added back original Anchor tags
=> fix: Rust doc fix

bindings/python/Cargo.lock, bindings/python/src/transform.rs
This patch chore the cargo.lock and fix the warning for python binding
=> fix: chore cargo lock and fix two warning for python bindings

bindings/python/tests/test_transform.py, crates/iceberg/src/transform/temporal.rs
=> Fix rounding of negative hour transform

.github/actions/overwrite-package-version/action.yml, .github/actions/setup-builder/action.yml
this patch make ci more safety using static check zizmor: to avoid code injection
more: 
- https://github.com/apache/airflow/issues/45408
- https://github.com/astral-sh/ruff/pull/14844
and github actions safety is more and more important:
link: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
=> fix: safety ci using static check zizmor

.github/dependabot.yml
None.
Group `arrow*` and `parquet` dependabot updates (https://github.com/apache/iceberg-rust/pulls?q=author%3Aapp%2Fdependabot+arrow).
No.
=> chore: group `arrow*` and `parquet` dependabot updates

.github/workflows/release_python.yml, .github/workflows/release_python_nightly.yml, bindings/python/project-description.md, bindings/python/pyproject.toml
When I go to:
https://pypi.org/project/pyiceberg_core/
It redirects to:
https://pypi.org/project/pyiceberg-core/
We also install `pyiceberg-core` in PyIceberg, so I think pypi automatically replaces the underscore with a dash.
=> Rename `pyiceberg_core` to `pyiceberg-core`

crates/iceberg/src/scan/mod.rs, crates/iceberg/testdata/example_empty_table_metadata_v2.json
Closes #1145.
Allow scanning of a table with no snapshots.
AFAICT, iceberg-python has [analogous
logic](https://github.com/apache/iceberg-python/blob/main/pyiceberg/table/__init__.py#L1684-L1686) to bail out when there is no snapshot.
Yes: `test_plan_files_on_table_without_any_snapshots`.
=> fix: support empty scans

crates/iceberg/Cargo.toml
Changes tokio dependency, enable `sync` feature only by default, but requires `full` feature when we enable `tokio` cfg. With this change, we can still use tokio's runtime indepdenent utils, while only rely on tokio's runtime when we enable `tokio` cfg.
CI.
=> Change tokio feature

Cargo.lock, crates/examples/Cargo.toml, crates/examples/src/oss_backend.rs, crates/iceberg/Cargo.toml, crates/iceberg/README.md, crates/iceberg/src/error.rs, crates/iceberg/src/io/mod.rs, crates/iceberg/src/io/storage.rs, crates/iceberg/src/io/storage_oss.rs
The support for AliyunOSS is based on OpenDAL, a production-verified project. Therefore, no additional testing has been added.
Add a new example.
=> feat(io): add OSS storage implementation

crates/iceberg/src/catalog/mod.rs, crates/iceberg/src/spec/table_metadata_builder.rs
This PR introduces the capability to remove schemas to enable expire snapshot action operations.
https://github.com/apache/iceberg/blob/456bbe98b0b0982278a61af4c44d32e1c27417e2/core/src/main/java/org/apache/iceberg/TableMetadata.java#L1177
https://github.com/apache/iceberg/blob/456bbe98b0b0982278a61af4c44d32e1c27417e2/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L249
refer to https://github.com/risingwavelabs/iceberg-rust/pull/20
- UT
=> feat(iceberg): introduce remove schemas

crates/catalog/rest/src/catalog.rs
- Closes #1247 
According to the [openapi spec](https://github.com/apache/iceberg-rust/issues/1247), already existed error should return 409 (Conflict) status code.
I checked with cargo test and doesn't find any breakage.
=> [catalog] Fix namespace creation error status

crates/iceberg/src/puffin/blob.rs, crates/iceberg/src/puffin/mod.rs
This PR adds deletion vector type constant (which is the counterpart for already-defined `APACHE_DATASKETCHES_THETA_V1`).
Reference: https://iceberg.apache.org/puffin-spec/#deletion-vector-v1-blob-type
=> chore: define deletion vector type constant

crates/iceberg/src/error.rs, crates/iceberg/src/transaction/append.rs, crates/iceberg/src/transaction/snapshot.rs
The general usage to append data files is
```rust
let mut action = txn.fast_append(/*commit_uuid=*/ None, /*key_metadata=*/ vec![])?;
action.add_data_files(new_data_files)?;
let txn = action.apply().await?;
let table = txn.commit(catalog).await?
```
I found if ` new_data_files` is empty by accident, a new manifest file will still be created and tracked by manifest list file, which doesn't make sense to me (let me if team thinks it's a valid and ideal use case).
In this PR, I did a few changes:
- Add a new invalid argument error code;
- Add assertion to fail empty data files append, and empty action commit use cases.
Existing unit tests pass, and add a validation test for invalid data file append.
=> chore: Add assertion for empty data files for append action

crates/iceberg/src/arrow/schema.rs
Helps https://github.com/apache/iceberg-rust/issues/1277
This expands the `test_type_conversion` test with the specific `DataType::Dictionary` type.
Props to @phillipleblanc for this, as I noticed the extra coverage on his PR which I believe is very useful to capture[^1].
[^1]: I was looking to add similar to https://github.com/apache/iceberg-rust/pull/1293, but it was merged just before I pushed the changes :laughing:
=> feat: expand arrow type conversion test

crates/iceberg/src/io/storage.rs
- Closes https://github.com/apache/iceberg-rust/issues/1303
This PR makes return type `Return<>` explicit.
I included a reproduction environment on the issue, and verify it compiles with no issue after my fix.
=> fix: Fix compilation failure when only storage-fs feature included

crates/iceberg/src/spec/manifest/writer.rs
This is the error message I get on my end:
```sh
Error: DataInvalid => Content type of entry PositionDeletes should have DataContentType::Data
```
At first sight, I have no idea what this means, until I read the sanity check code.
In this PR, I updated the error message for manifest write sanity check to provide more context:
- What's the manifest content file
- What's the filepath, this is useful for devs to directly understand what's the data file having issues
- What's the expected and actual data content type
No-op change
=> chore: minor update to manifest sanity check error message

crates/iceberg/src/io/file_io.rs
- Closes https://github.com/apache/iceberg-rust/issues/1318
Declare `FileRead` trait `Sync`-safe.
Not a feature change, so existing unit tests.
=> chore: declare `FileRead` trait to be `Sync`-safe

crates/iceberg/src/catalog/mod.rs
- Closes #1262 .
Update doc.
No.
=> Add doc for TableCommit

.github/workflows/bindings_python_ci.yml
None
While reviewing PRs related to the python bindings, I noticed that the code formatting was incorrect and some clippy lints were not being triggered properly.
This happened because we weren't running the checks on the correct path. This PR addresses that issue.
Our Python friends should be happier and feel more at home with Rust now.
Not needed, it's in CI.
=> ci: Fix python bindings rust code not checked

.gitignore
None
I'm currently using `zed` (it's great, I highly recommend it!). 
I needed to add the following RA settings:
```json
{
"rust-analyzer": {
"linkedProjects": ["./Cargo.toml", "./bindings/python/Cargo.toml"]
}
}
```
This allows RA to work with the Python bindings as well.
I'm going to add `.zed` to the gitignore file so I don't accidentally include it.
=> chore: Ignore .zed settings dir

scripts/dependencies.py
- Related to #1325.
`DEPENDENCIES.rust.tsv` files were accidentally removed as part of the 0.5.0 prep PR (#1345). It was added back and updated in the follow up PR (#1363). 
I realized this happened because I did not install `cargo-deny` in my env and the dependency generation script did not error. 
This PR changes generation script (`python3 ./scripts/dependencies.py generate`) to error when the underlying subprocess call (`cargo deny`) errors. 
I also ran `uvx ruff format scripts/dependencies.py` to format the script
Yes, manually
I was also able to install `cargo-deny` and confirm #1363 changes are all correct
```
cargo install --locked cargo-deny
```
=> Make `dependencies.py generate` fail on cargo-deny error

crates/iceberg/src/arrow/reader.rs
N/A
This PR is to fix a bug in checking if a leaf column is root column in Parquet schema. The current solution is to compare the leaf column's index with root column's index, this is not reliable as the column index may not correspond exactly after a nested column. For example,
- col A: String
- col B: Map
- key B.K: String
- value B.V: String
- col C: String
For column A, B.K and B.V, the currently logic works well. It won't return error for A, but will do for B.K and B.V, this is correct. But for column C, it will return error as its leaf column index (3) will not match root column index (2), this is incorrect. Column C is a valid leaf column to be in a predicate.
I think `get_column_root().is_group()` may be a more reliable way to check in this situation. Just to check if a leaf …
=> fix: check leaf column is root column in Parquet schema

crates/iceberg/src/io/storage_azdls.rs
- Relates to #1360.
I tested again fileIO operations with the `wasbs://` scheme, and the current implementation mistakenly used the `blob` endpoint which is lacking the ADLS APIs.
The code now always uses the `dfs` endpoint, regardless of whether a user passes `wasb[s]://` or `abfs[s]://`. Because the `AzureStoragePath::storage_service` field isn't read, I've removed it.
Yes, I added a new unit test for the `AzureStoragePath::endpoint` method.
=> bug(storage-azdls): Fix inferred WASB endpoint

crates/iceberg/src/spec/table_metadata.rs
We are currently missing public accessors for `last_column_id` and `last_partition_id` as part of `TableMetadata`.
=> feat: Public accessors for `last_column_id` and `last_partition_id`

website/src/release.md
- Closes #.
Update link to how to verify release.
Ran `mdbook serve` locally and verified.
=> Update link to how to verify release.

crates/catalog/rest/src/catalog.rs, crates/catalog/rest/src/client.rs
- Partially implements #437
Per discussion here: https://github.com/apache/iceberg-rust/issues/437#issuecomment-2997408926
This branch exposes two public methods on the rest catalog for managing tokens: `invalidate_token` and `regenerate_token`.
- `invalidate_token`: takes the token lock and sets the token to `None`, forcing re-auth on the next request
- `regenerate_token`: calls the oauth endpoint to generate a new token. if successful, takes the token lock and writes the new token.
Yes -- I've added new unit tests to cover both methods.
=> feat(iceberg-catalog-rest): expose invalidate_token, regenerate_token APIs

crates/iceberg/src/io/storage_azdls.rs
Currently we don't have a way to create a `FileIO` for adls with a non-default Authority host. Opendal already supports this feature, so we only need to pass the configuration.
Expose a property `adls.authority-host` that sets the corresponding Opendal configuration
No, do we need to?
=> feat: Support non-default adls-authority-host

crates/iceberg/src/spec/schema/mod.rs
Motivation:
- I would like to leverage naming mapping, to compensate the issue that table metadata reassigns field id on creation.
- Name mapping requires (1) field id; (2) field name; (3) children values; all these information could be fetched from `Schema`, but could be a lot easier and performant if we could expose (1) field id -> field name; (2) field id -> field mapping.
N/A, trivial visibility change, no functional change
=> chore: expose field id mapping from schema

Cargo.lock, crates/catalog/rest/src/catalog.rs, crates/iceberg/Cargo.toml, crates/iceberg/src/io/file_io.rs, crates/iceberg/src/io/storage.rs, crates/iceberg/src/io/storage_s3.rs, crates/iceberg/tests/file_io_s3_test.rs
- Closes #1527
Adds the ability to provide custom extensions to the `FileIOBuilder`. Currently the only supported extension is `CustomAwsCredentialLoader` which is a newtype around [`AwsCredentialLoad`](https://docs.rs/reqsign/0.16.3/reqsign/trait.AwsCredentialLoad.html), which is what OpenDAL expects.
I've added extensions to the `RestCatalog` as well, and when its constructing `FileIO` for table operations, passes along any defined extensions into the `FileIOBuilder`, which then get passed into the underlying OpenDAL constructors.
Yes, tests added in `crates/iceberg/tests/file_io_s3_test.rs` that verify the extension is working.
=> Add support for custom credential loader for S3 FileIO

bindings/python/pyproject.toml, bindings/python/tests/test_datafusion_table_provider.py, crates/integrations/datafusion/src/table/mod.rs, crates/integrations/datafusion/tests/integration_datafusion_test.rs
- Closes #.
* Previous #1600 added few integration tests, but need to include the new changes introduced in memory catalog loader change #1623 .
* This caused build failures
Yes, existing tests
=> fix: await get catalog in datafusion integration test and update version in python binding

.github/workflows/ci.yml
- Closes #.
Context: https://github.com/apache/iceberg-rust/issues/1195#issuecomment-3262641348
[the docs](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#minimal-versions) mentions that the feature is not recommended anymore
I've ran an issue with this flag when upgrading datafusion from 47 -> 48. -Z minimal-versions will pull in very old versions of transitive dependencies
=> ci: only use `-Z direct-minimal-versions` for MSRV check

CHANGELOG.md, bindings/python/DEPENDENCIES.rust.tsv, crates/catalog/glue/DEPENDENCIES.rust.tsv, crates/catalog/hms/DEPENDENCIES.rust.tsv, crates/catalog/loader/DEPENDENCIES.rust.tsv, crates/catalog/rest/DEPENDENCIES.rust.tsv, crates/catalog/s3tables/DEPENDENCIES.rust.tsv, crates/catalog/sql/DEPENDENCIES.rust.tsv, crates/examples/DEPENDENCIES.rust.tsv, crates/iceberg/DEPENDENCIES.rust.tsv, crates/iceberg/src/arrow/reader.rs, crates/iceberg/src/spec/datatypes.rs, crates/iceberg/src/spec/view_version.rs, crates/integration_tests/DEPENDENCIES.rust.tsv, crates/integrations/cache-moka/DEPENDENCIES.rust.tsv, crates/integrations/datafusion/DEPENDENCIES.rust.tsv, crates/integrations/playground/DEPENDENCIES.rust.tsv, crates/sqllogictest/DEPENDENCIES.rust.tsv, crates/test_utils/DEPENDENCIES.rust.tsv, rust-toolchain.toml
- A part of #1631 
- Bumped toolchain version to rust 1.87 and fixed clippy accordingly
- updated dependencies list
=> chore: Bump toolchain version to rust 1.87 and update dependencies list

website/src/release.md
- Closes #.
Based on notes from #1631 and past experience running the release process
A few things to know
* we use `v${release_version}` format as the tag 
* we use the `apache-iceberg-rust-${release_version}/` format for ASF svn (for [dev](https://dist.apache.org/repos/dist/dev/iceberg/) and [release](https://dist.apache.org/repos/dist/release/iceberg/) )
=> docs: update "how to release"

crates/iceberg/src/avro/schema.rs
`Fixed[16]` encoded UUIDs are now supported in Avro-rs: https://github.com/apache/avro-rs/pull/255
This will automatically support String and Fixed[16] logical types if the `logicalType` annotation is set correctly 👍
=> Add UUID support for the Avro schema
